# Irish Wind Speed Analysis Using Historic Met Éireann Weather Data

In [17]:
# Import required libraries
import pandas as pd
import matplotlib.pyplot as plt

## Project Dataset
In this project, I analyse wind speed data from across Ireland. To represent different regional conditions, data from the following weather stations has been selected:

- Malin Head (county Donegal) – north-west coastline
- Mace Head (county Galway) - Atlantic west coast 
- Dublin Airport (Dublin) - east coast

Historical wind speed data was obtained from [Met Éireann](https://www.met.ie/climate/available-data/historical-data). The data was downloaded locally and stored in the `data` folder within this project. Each folder contains the CSV file used for analysis, along with additional documentation and licence files, which are retained for reference and data governance purposes.

## Validate data repository structure

To load the datasets, the `pd.read_csv()` function requires the correct file paths. Before loading any data, the project directory is checked to confirm that the expected folders and CSV files are present.

A dictionary is created to store the data directory paths for each weather station, where the keys represent the station names and the values represent the corresponding folder locations. The contents of each directory are then printed using the `for loop` to verify that the required files are available. Iterating through the dictionary approach is adapted from the following [Real Python](https://realpython.com/iterate-through-dictionary-python/) tutorial.

In [ ]:
# Create a dictionary to hold weather station data folders
data_dirs = {
    "Malin Head": "../project/data/malin_head/",
    "Mace Head": "../project/data/mace_head/",
    "Dublin Airport": "../project/data/dublin_airport/"
}

# List contents of each data directory using for loop
for station, path in data_dirs.items():
    print(f"\nContents of {station} directory:")
    !ls "{path}"

Repository content for Malin Head:
Data_Licence.pdf Data_Licence.txt KeyHourly.txt    hly1575.csv

Repository content for Mace Head:
Data_Licence.pdf Data_Licence.txt KeyHourly.txt    hly275.csv

Repository content for Dublin Airport:
Data_Licence.pdf Data_Licence.txt KeyHourly.txt    hly532.csv

## Function for loading data

Since multiple datasets are used in this project, a function is created to handle data loading in a consistent way.

Based on a manual inspection of the CSV files, the function needs to account for the following:

- Each CSV file contains introductory metadata rows before the actual data begins, which should be skipped.  
  - Malin Head and Dublin Airport require skipping the first 23 rows  
  - Mace Head requires skipping the first 17 rows
- All datasets contain a common **"Date"** column. This column will be converted to datetime format and set as the DataFrame index to make time-based analysis easier.

In [30]:
def load_data(file_path, skiprows):
    """Load hourly weather data from a CSV file into a pandas DataFrame."""

    # Read the CSV file into a DataFrame using low_memory=False to avoid dtype warning
    df = pd.read_csv(file_path, skiprows=skiprows, low_memory=False)

    # Convert 'date' column to datetime format
    # Pass 'mixed' to handle different date formats in the column (without format argument pandas shows warning)
    df['date']= pd.to_datetime(df['date'], format='mixed')
    
    # Set 'date' column as index
    df = df.set_index('date')
    
    return df

## Load Malin Head dataset

In [41]:
# Define file path for Malin Head data
malin_data_dir = "../project/data/malin_head/"
malin_file = "hly1575.csv"
malin_file = malin_data_dir + malin_file

# Load Malin Head data (skip first 23 rows)
malin_df = load_data(malin_file, skiprows=23)

# Show first 5 rows
malin_df.head(5)

,ind,rain,ind.1,temp,ind.2,wetb,dewpt,vappr,rhum,msl,ind.3,wdsp,ind.4,wddir,ww,w,sun,vis,clht,clamt
date,,,,,,,,,,,,,,,,,,,,
1955-05-01 01:00:00,0,0.0,0,8.5,0,7.2,5.5,9.1,83,1005.6,0,11,0,130,3,2,0.0,30000,40,7
1955-05-01 02:00:00,0,0.0,0,8.2,0,7.2,6.1,9.3,85,1004.4,0,11,0,120,1,2,0.0,30000,100,6
1955-05-01 03:00:00,3,0.0,0,7.3,0,6.6,5.5,9.3,91,1003.8,0,8,0,120,1,2,0.0,30000,220,5
1955-05-01 04:00:00,3,0.0,0,7.8,0,7.2,6.1,9.6,91,1002.7,0,18,0,130,3,2,0.0,30000,90,7
1955-05-01 05:00:00,0,0.0,0,8.1,0,7.3,6.6,9.7,89,1002.1,0,9,0,110,2,2,0.0,40000,90,7

## Load Mace Head dataset

In [39]:
# Define file path for Mace Head data
mace_data_dir = "../project/data/mace_head/"
mace_filename = "hly275.csv"
mace_file = mace_data_dir + mace_filename

# Load Mace Head data (skip first 17 rows)
mace_df = load_data(mace_file, skiprows=17)

# Show first 5 rows
mace_df.head(5)

,ind,rain,ind.1,temp,ind.2,wetb,dewpt,vappr,rhum,msl,ind.3,wdsp,ind.4,wddir
date,,,,,,,,,,,,,,
2003-08-13 01:00:00,-1,,4,,4,,,,,,7,,7,
2003-08-13 02:00:00,-1,,4,,4,,,,,,7,,7,
2003-08-13 03:00:00,-1,,4,,4,,,,,,7,,7,
2003-08-13 04:00:00,-1,,4,,4,,,,,,7,,7,
2003-08-13 05:00:00,-1,,4,,4,,,,,,7,,7,

## Load Dublin Airport dataset

In [ ]:
# Define file path for Dublin Airport data
dublin_data_dir = "../project/data/dublin_airport/"
dublin_filename = "hly532.csv"
dublin_file = dublin_data_dir + dublin_filename

# Load Dublin Airport data (skip first 23 rows)
dublin_df = load_data(dublin_file, skiprows=23)

# Show first 5 rows
dublin_df.head(5)

,ind,rain,ind.1,temp,ind.2,wetb,dewpt,vappr,rhum,msl,ind.3,wdsp,ind.4,wddir,ww,w,sun,vis,clht,clamt
date,,,,,,,,,,,,,,,,,,,,
1945-01-01 00:00:00,2,0.0,0,4.9,0,4.6,4.4,8.2,95,1035.8,1,0,1,0,50,4,0.0,200,2,8
1945-01-01 01:00:00,3,0.0,0,5.1,0,4.9,4.4,8.5,97,1035.8,1,0,1,0,45,4,0.0,200,2,8
1945-01-01 02:00:00,2,0.0,0,5.1,0,4.8,4.4,8.5,97,1035.8,1,0,1,0,50,4,0.0,4800,4,8
1945-01-01 03:00:00,0,0.2,0,5.2,0,5.0,4.4,8.5,97,1036.1,1,0,1,0,50,4,0.0,6000,4,8
1945-01-01 04:00:00,2,0.0,0,5.6,0,5.4,5.0,8.8,97,1036.2,1,7,1,250,50,5,0.0,6000,4,8

## End